### ISSUE TITLE
Relase-B-Volta-Deployment-(before-Monorepo) - Deployment to Volta Failed

### ISSUE THREAD

**Issue by oxfordssherwanic** [energywebfoundation/origin#30]
This is in regards to the https://github.com/energywebfoundation/origin/wiki/Relase-B-Volta-Deployment-(before-Monorepo)

My deployment is failing with Origin UI giving me the error..
index.js?bbaf:226 Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas?
  

It seems ew-utils-demo-master did not start correctly.
The coresponding logs are as below..
verbose: Got off chain properties from http://0.0.0.0:3030/ConsumingAsset/0
verbose: Consuming asset 0 synced
-----------------------------------------------------------

sleep
-----------------------------------------------------------
info: Certificates for Asset #0 initialized
-----------------------------------------------------------
-----------------------------------------------------------
/home/ubuntu/buffalogap/ew-utils-demo-master/node_modules/ew-asset-registry-lib/
                        const outputResult = r.result.output;
                                                      ^

TypeError: Cannot read property 'output' of undefined

The URL http://0.0.0.0:3030 is coming from API_BASE_URL under ew-utils-demo-master/src/config.ts

What should be the value of API_BASE_URL?
Are there any other additional configurations beyond connection-config.json?
I am using the default accounts already defined under config/contractConfig.json for Volta deployment. Is that fine?

**Comment by e00dan** [comment]
1. Did you run `npm run start-test-backend` in `ew-utils-demo` to start backend service (this information was missing in the guide)?

2. After starting backend, when you go to `http://0.0.0.0:3030` or `http://localhost:3030` or `http://127.0.0.1:3030` do you see following text:

```
Cannot GET /
```

?

If answer to Question 2 is yes, then it means backend should be working correctly.

[I've updated the instructions how to deploy release B to Volta. Please check it out, they are more detailed now.](https://github.com/energywebfoundation/origin/wiki/Relase-B-Volta-Deployment-(before-Monorepo))

I've just cloned `ew-utils-demo` and tried the instructions (updated them as I worked) and I managed to deploy without errors:
![Screenshot from 2019-09-11 19-39-27](https://user-images.githubusercontent.com/4950658/64721270-60905780-d4cc-11e9-8c58-e2cdf11b5a70.png)
![Screenshot from 2019-09-11 19-39-32](https://user-images.githubusercontent.com/4950658/64721282-66863880-d4cc-11e9-990d-fd787eb16782.png)

Regarding your questions:

> What should be the value of API_BASE_URL?

It should be address where `npm run start-test-backend` command is running a backend server. This URL should be accessible in browser. For example `localhost:3030` should return:
```
Cannot GET /
```

> Are there any other additional configurations beyond connection-config.json?

There is configuration of `ew-origin-ui`, a need to change `.env.dev` or `.env.prod` depending what you're using. More info added to the wiki page.

> I am using the default accounts already defined under config/contractConfig.json for Volta deployment. Is that fine?

Yes, they are fine. If you find yourself missing some Volta tokens for gas use the faucet: https://voltafaucet.energyweb.org

cc @oxfordssherwanic

**Comment by oxfordssherwanic** [comment]
Thank you. How many tokens/min gas I should have to bring up Origin UI.

**Comment by e00dan** [comment]
@oxfordssherwanic 

Less than 1 token should be enough for deploying Origin multiple times, while faucet gives 1 token.

It's unlikely that you will hit problems with not having enough tokens. The gas price is low on chain.

**Comment by oxfordssherwanic** [comment]
Ok. thank you. The :3030 URL is working for me in the browser, the account has enough tokens, but I still see the attached error. Could you please help what else could be causing the issue and how do I troubleshoot it. The project was working fine when I had it local.
![ERROR-VOLTA](https://user-images.githubusercontent.com/47336427/64862808-6f2c5b00-d601-11e9-9fab-9a5e23ab8f34.GIF)
![ERROR-VOLTA-SCREEN](https://user-images.githubusercontent.com/47336427/64862809-6fc4f180-d601-11e9-954a-0afae1a00459.GIF)
![TOKENS_EWF](https://user-images.githubusercontent.com/47336427/64862810-6fc4f180-d601-11e9-8ba5-24d5d0c3ea9d.GIF)
![volta-3030](https://user-images.githubusercontent.com/47336427/64862811-6fc4f180-d601-11e9-8758-d91cb67d98b1.GIF)

**Comment by oxfordssherwanic** [comment]
I am using the default accounts that come with configuration. Should those be diffferent?

**Comment by oxfordssherwanic** [comment]
Please see the log errors.
[VOLTA_ERROR.docx](https://github.com/energywebfoundation/origin/files/3610225/VOLTA_ERROR.docx)

**Comment by e00dan** [comment]
Did you choose local Ganache RPC address in MetaMask?

For example you should have localhost:8545 if you run local Ganache. If problem persists try to switch in MetaMask from local network to other network for example main net and then back to local, because MetaMask is sometimes buggy and choosing different network and reselecting local network  resets it and it should work.

@oxfordssherwanic

**Comment by e00dan** [comment]
Also, I want to make sure you're running correct versions. Could you share output of these commands ran in `ew-utils-demo` directory?

```
git status
git diff
git log
node -v
npm -v
```

cc @oxfordssherwanic

**Comment by oxfordssherwanic** [comment]
Hi. 
ew-utils-demo-master$ git status
fatal: Not a git repository (or any of the parent directories): .git
ew-utils-demo-master$ git diff
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
ew-utils-demo-master$ git log
fatal: Not a git repository (or any of the parent directories): .git
ew-utils-demo-master$ node -v
v10.9.0
ew-utils-demo-master$ npm -v
6.2.0
ew-utils-demo-master$

It was copied as zip from GIT. It's fully functional locally.

**Comment by oxfordssherwanic** [comment]
Did you choose local Ganache RPC address in MetaMask?
Response: No I completely shut down local Ganache, If I start it, then contracts deploy on local despite of providing the URL of Volta.

**Comment by oxfordssherwanic** [comment]
I keep on getting attached VOLTA error. Should I change anything for it?

**Comment by e00dan** [comment]
Hello, commands: `git diff, git log, git status` are very important so I can see the changes you have in your setup and also verify that you're using latest versions.

Could you please start the process from inside directory which contains Git directory (it is recommended way) instead of copying it from ZIP?

---

> No I completely shut down local Ganache, If I start it, then contracts deploy on local despite of providing the URL of Volta.

This looks like a sign that not everything is configured.

> I keep on getting attached VOLTA error. Should I change anything for it?

No, you can keep using Volta.

BTW. For me the only change I had to make, and this is my `git diff` output for working setup is this:
```
diff --git a/connection-config.json b/connection-config.json
index f1fa6cc..bdacb71 100644
--- a/connection-config.json
+++ b/connection-config.json
@@ -1,6 +1,6 @@
 {
     "develop": {
-        "web3": "http://localhost:8545",
+        "web3": "https://volta-rpc.energyweb.org",
         "deployKey": "d9066ff9f753a1898709b568119055660a77d9aae4d7a4ad677b8fb3d2a571e5"
     }
 }
\ No newline at end of file
(END)
```

cc @oxfordssherwanic

**Comment by oxfordssherwanic** [comment]
I have emailed the requested info. Thanks.

**Comment by oxfordssherwanic** [comment]
With fixed configuration and getting latest code for UI from GIT, I am able to bring the UI up. However I am not able to switch between users anymore - it's always guest. I have sent out the output of git diff, status and log. Thanks.
